<template>
  <div>
    <breadcrump :paths-list="pathsList" breadcrump-class="breadcrump-link">
    </breadcrump>
    <!-- ***** Welcome Area Start ***** -->
    <welcome-area-start
      :text-button="textButton"
      link="#visionsContainers"
      :bigImage="bigImage"
    >
      <template #title> Our Areas: <br /><em>The Visions</em> </template>
      <template #overview>
        Having a <b>Vision</b> means offering a look into the future.<br />
        A <i>tour</i> through our invations, a <i>journey</i> lead by our
        immagination, an <i>experience</i> generated by our passions. Our
        Visions are not just the way we look at the world, but rather the ways
        the world suggest us to take.
      </template>
    </welcome-area-start>
    <section id="visionsContainers">
      <content-rounded-containers
        :content="visions"
        :area-name="areaName"
        :image-name="'image'"
        typology="visions"
        research-id=""
        description="Discover our four product areas"
      >
      </content-rounded-containers>
    </section>
  </div>
</template>

<script>
import Breadcrump from "~/components/baseElements/Breadcrump.vue";
import WelcomeAreaStart from "~/components/baseElements/WelcomeAreaStart.vue";
import ContentRoundedContainers from "~/components/baseElements/ContentRoundedContainers";

export default {
  components: {
    Breadcrump,
    WelcomeAreaStart,
    ContentRoundedContainers,
  },
  async asyncData({ $axios }) {
    const { data } = await $axios.get(`${process.env.BASE_URL}/api/visions`);
    const visions = data;
    return {
      visions,
    };
  },
  data() {
    return {
      bigImage: "/banners/banner-player.png",
      textButton: "DISCOVER OUR VISIONS",
      areaName: "Our Visions",
      pathsList: [
        {
          path: this.$route.path,
          pathName: "Visions",
        },
      ],
    };
  },
  head() {
    return {
      title: "Invation - All visions",
      meta: [
        {
          name: "description",
          content: "All the visions of the Invation Team",
        },
        {
          hid: "all visions",
          name: "all visions",
          content: "all visions overview and visions presentation",
        },
      ],
    };
  },
  /* In this case this mounted() is useless because the names of the attributes used inside the 
  ContentRoundedContainers are the same of those in the Vision schema of the DB, 
  however it shows the way to use properly the  component ContentRoundedContainers
  mounted() {
    for (let i = 0; i < this.visions.length; i++) {
      const newVision = {
        name: this.visions[i].name,
        numberTag: this.visions[i].numberTag,
        description: this.visions[i].description,
        image: this.visions[i].image,
        typology: 'visions',
      }
      this.myVisions.push(newVision)
    }
  },
  */
};
</script>

<style></style>
