<!-- Group introductory page for the areas (visions) -->
<template>
  <div>
    <!-- Orientation info component -->
    <breadcrump :paths-list="pathsList" breadcrump-class="breadcrump-link">
    </breadcrump>
    <!--  Page introduction  -->
    <welcome-area-start
      text-button="DISCOVER OUR VISIONS"
      link="#visionsContainers"
      bigImage="/banners/banner-player.png"
    >
      <template #title> Our Areas: <br /><em>The Visions</em> </template>
      <template #overview>
        Having a <b>Vision</b> means offering a look into the future.<br />
        A <i>tour</i> through our invations, a <i>journey</i> lead by our
        immagination, an <i>experience</i> generated by our passions. Our
        Visions are not just the way we look at the world, but rather the ways
        the world suggest us to take.
      </template>
    </welcome-area-start>
    <!-- List of the visions -->
    <section id="visionsContainers">
      <content-rounded-containers
        :content="visions"
        area-name="Our Visions"
        :image-name="'image'"
        typology="visions"
        description="Discover our four product areas"
      >
      </content-rounded-containers>
    </section>
  </div>
</template>

<script>
import Breadcrump from "~/components/baseElements/Breadcrump.vue";
import WelcomeAreaStart from "~/components/baseElements/WelcomeAreaStart.vue";
import ContentRoundedContainers from "~/components/baseElements/ContentRoundedContainers";

export default {
  components: {
    Breadcrump,
    WelcomeAreaStart,
    ContentRoundedContainers,
  },
  // Get all visions
  async asyncData({ $axios }) {
    const { data } = await $axios.get(`${process.env.BASE_URL}/api/visions`);
    const visions = data;
    return {
      visions,
    };
  },
  data() {
    return {
      // Information used for the breadcrump functionalities
      pathsList: [
        {
          path: this.$route.path,
          pathName: "Visions",
        },
      ],
    };
  },
  head() {
    return {
      title: "Invation - All visions",
      meta: [
        {
          name: "description",
          content: "All the visions of the Invation Team",
        },
        {
          hid: "all visions",
          name: "all visions",
          content: "all visions overview and visions presentation",
        },
      ],
    };
  },
};
</script>

<style></style>
