<template>
  <div>
    <!-- ***** Welcome Area Start ***** -->
    <WelcomeAreaStart :text-button="textButton">
      <template #title> A Look Into the Future: <em>Our Visions</em> </template>
      <template #overview>
        Having a <b>Vision</b> means offering a look into the future.<br />
        A <i>tour</i> through our invations, a <i>journey</i> lead by our
        immagination, an <i>experience</i> generated by our passions. Our
        Visions are not just the way we look at the world, but rather the ways
        the world suggest us to take.
      </template>
    </WelcomeAreaStart>
    <ContentRoundedContainers :content="visions" :area-name="areaName">
    </ContentRoundedContainers>
  </div>
</template>

<script>
import WelcomeAreaStart from '~/components/baseElements/WelcomeAreaStart.vue'
import ContentRoundedContainers from '~/components/vision/ContentRoundedContainers'

export default {
  components: { WelcomeAreaStart, ContentRoundedContainers },
  async asyncData({ $axios }) {
    const { data } = await $axios.get(`${process.env.BASE_URL}/api/visions`)
    const visions = data
    return {
      visions,
    }
  },
  data() {
    return {
      textButton: 'DISCOVER INVATIONERS ROLES',
      areaName: 'Our Visions',
    }
  },
}
</script>

<style></style>
