<template>
  <div>
    <!-- ***** Welcome Area Start ***** -->
    <WelcomeAreaStart :text-button="textButton">
      <template v-slot:title>
        A Look Into the Future: <em>Our Visions</em>
      </template>
      <template v-slot:overview>
        Having a <b>Vision</b> means offering a look into the future.<br />
        A <i>tour</i> through our invations, a <i>journey</i> lead by our
        immagination, an <i>experience</i> generated by our passions. Our
        Visions are not just the way we look at the world, but rather the ways
        the world suggest us to take.
      </template>
    </WelcomeAreaStart>
    <!--<ContentRoundedContainers> </ContentRoundedContainers>-->
  </div>
</template>

<script>
import WelcomeAreaStart from '~/components/baseElements/WelcomeAreaStart.vue'
// import ContentRoundedContainers from '~/components/Vision/ContentRoundedContainers'

export default {
  components: { WelcomeAreaStart },
  async asyncData({ $axios }) {
    const { data } = await $axios.get(`${process.env.BASE_URL}/api/visions`)
    const visions = data
    return {
      visions,
    }
  },
  data() {
    return {
      textButton: 'DISCOVER INVATIONERS ROLES',
    }
  },
}
</script>

<style></style>
